apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  labels:
    app: brain-tasks-app
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - port: 3000
      




